targets:
  $default:
    sources:
      - swagger/**
    builders:
      swagger_dart_code_generator:
        options:
          with_converter: true
          input_folder: "swagger/"
          output_folder: "lib/swagger/"